# Generated by Django 5.0.6 on 2024-07-09 10:36

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="properties",
            field=django_jsonform.models.fields.JSONField(default=dict),
        ),
    ]
