import citeproc.types
from django.db import models
from django.utils.translation import gettext as _

CSL_TYPE_CHOICES = [
    (
        _("Academic and Professional"),
        [
            ("paper-conference", _("Conference paper")),
            ("dataset", _("Dataset")),
            ("article-journal", _("Journal Article")),
            ("report", _("Report")),
            ("standard", _("Standard")),
        ],
    ),
    (
        _("Books and Written Works"),
        [
            ("book", _("Book")),
            ("chapter", _("Book chapter")),
            ("classic", _("Classic work")),
            ("collection", _("Collection of works")),
            ("manuscript", _("Manuscript")),
            ("thesis", _("Thesis")),
        ],
    ),
    (
        _("Legislation and Legal"),
        [
            ("bill", _("Legislative bill")),
            ("hearing", _("Congressional hearing")),
            ("legal_case", _("Legal case")),
            ("legislation", _("Legislation")),
            ("patent", _("Patent")),
            ("regulation", _("Regulation")),
            ("treaty", _("Treaty")),
        ],
    ),
    (
        _("Media and Communication"),
        [
            ("broadcast", _("Broadcast")),
            ("interview", _("Interview")),
            ("article-magazine", _("Magazine Article")),
            ("article-newspaper", _("Newspaper Article")),
            ("speech", _("Speech")),
        ],
    ),
    (
        _("Visual and Creative"),
        [
            ("figure", _("Figure or illustration")),
            ("graphic", _("Graphic work")),
            ("map", _("Map")),
            ("motion_picture", _("Motion picture")),
            ("musical_score", _("Musical score")),
            ("performance", _("Live performance")),
            ("software", _("Software")),
            ("song", _("Song")),
        ],
    ),
    (
        _("Periodicals and Reviews"),
        [
            ("periodical", _("Generic periodical")),
            ("review", _("Review")),
            ("review-book", _("Book review")),
        ],
    ),
    (
        _("Digital and Online Content"),
        [
            ("post", _("Blog post")),
            ("post-weblog", _("Weblog post")),
            ("webpage", _("Webpage")),
        ],
    ),
    (
        _("Miscellaneous"),
        [
            ("article", _("Generic Article")),
            ("document", _("Generic Document")),
            ("entry", _("Generic Entry")),
            ("entry-dictionary", _("Dictionary Entry")),
            ("entry-encyclopedia", _("Encyclopedia Entry")),
            ("event", _("Event")),
            ("pamphlet", _("Pamphlet")),
            ("personal_communication", _("Personal communication")),
        ],
    ),
]

# These fields are explicitly shown in the form when the given type is selected by the user.
# If a field does not appear in any list, it will be shown for all types.
CSL_SUGGESTED_PROPERTIES = {
    "article": [
        "author",
        "title",
        "title-short",
        "container-title",
        "container-title-short",
        "issue",
        "number",
        "page",
        "publisher-place",
        "edition",
        "issued",
        "collection-number",
        "collection-title",
        "section",
        "status",
        "supplement-number",
        "volume",
        "volume-title",
    ],
    "article-journal": [
        "author",
        "title",
        "container-title",
        "volume",
        "page",
        "issued",
        "DOI",
        "URL",
    ],
    "article-magazine": [
        "author",
        "title",
        "container-title",
        "volume",
        "page",
        "issued",
        "DOI",
        "URL",
    ],
    "article-newspaper": [
        "author",
        "title",
        "container-title",
        "volume",
        "page",
        "issued",
        "DOI",
        "URL",
    ],
    "bill": [
        "title",
        "jurisdiction",
        "authority",
        "URL",
    ],
    "book": [
        "author",
        "collection_editor",
        "title",
        "publisher",
        "publisher-place",
        "volume",
        "edition",
        "issued",
        "ISBN",
        "DOI",
        "URL",
    ],
    "broadcast": [
        "title",
        "event-date",
        "medium",
        "URL",
    ],
    "chapter": [
        "author",
        "title",
        "container-title",
        "volume",
        "page",
        "publisher",
        "publisher-place",
        "issued",
        "ISBN",
        "DOI",
        "URL",
    ],
    "classic": [
        "author",
        "title",
        "publisher",
        "publisher-place",
        "volume",
        "edition",
        "issued",
        "ISBN",
        "URL",
    ],
    "collection": [
        "editor",
        "collection_editor",
        "title",
        "publisher",
        "publisher-place",
        "volume",
        "edition",
        "issued",
        "ISBN",
        "URL",
    ],
    "dataset": [
        "author",
        "title",
        "publisher",
        "publisher-place",
        "issued",
        "URL",
        "compiler",
        "license",
    ],
    "document": [
        "author",
        "title",
        "publisher",
        "publisher-place",
        "issued",
        "ISBN",
        "DOI",
        "license",
        "URL",
    ],
    "entry": [
        "title",
        "container-title",
        "publisher",
        "publisher-place",
        "issued",
        "ISBN",
        "DOI",
        "URL",
    ],
    "entry-dictionary": [
        "title",
        "container-title",
        "publisher",
        "publisher-place",
        "issued",
        "ISBN",
        "DOI",
        "URL",
    ],
    "entry-encyclopedia": [
        "title",
        "container-title",
        "publisher",
        "publisher-place",
        "issued",
        "ISBN",
        "DOI",
        "URL",
    ],
    "event": [
        # "title",
        "event",
        "event-place",
        "event-title",
        "event-date",
        "chair",
        "URL",
    ],
    "figure": [
        "title",
        "creator",
        "dimensions",
        "URL",
    ],
    "graphic": [
        "title",
        "creator",
        "illustrator",
        "dimensions",
        "URL",
    ],
    "hearing": [
        "title",
        "event-date",
        "jurisdiction",
        "authority",
        "URL",
    ],
    "interview": [
        "interviewer",
        "title",
        "container-title",
        "volume",
        "page",
        "issued",
        "DOI",
        "URL",
    ],
    "legal_case": [
        "title",
        "jurisdiction",
        "authority",
        "URL",
    ],
    "legislation": [
        "title",
        "jurisdiction",
        "authority",
        "URL",
    ],
    "manuscript": [
        "author",
        "title",
        "publisher",
        "publisher-place",
        "issued",
        "ISBN",
        "DOI",
        "URL",
    ],
    "map": [
        "author",
        "title",
        "publisher",
        "publisher-place",
        "issued",
        "scale",
        "ISBN",
        "DOI",
        "URL",
    ],
    "motion_picture": [
        "director",
        "executive-producer",
        "title",
        "container-title",
        "guest",
        "host",
        "narrator",
        "volume",
        "page",
        "issued",
        "medium",
        "DOI",
        "URL",
    ],
    "musical_score": [
        "author",
        "composer",
        "title",
        "publisher",
        "publisher-place",
        "volume",
        "edition",
        "issued",
        "ISBN",
        "DOI",
        "URL",
    ],
    "pamphlet": [
        "author",
        "title",
        "publisher",
        "publisher-place",
        "volume",
        "edition",
        "issued",
        "ISBN",
        "DOI",
        "URL",
    ],
    "paper-conference": [
        "author",
        "title",
        "container-title",
        "event-date",
        "page",
        "publisher",
        "publisher-place",
        "issued",
        "DOI",
        "URL",
    ],
    "patent": [
        "title",
        "authority",
        "URL",
    ],
    "performance": [
        "performer",
        "title",
        "event-date",
        "medium",
        "URL",
    ],
    "periodical": [
        "editor",
        "title",
        "container-title",
        "volume",
        "page",
        "issued",
        "DOI",
        "URL",
    ],
    "personal_communication": [
        "author",
        "title",
        "URL",
    ],
    "post": [
        "author",
        "title",
        "container-title",
        "volume",
        "page",
        "issued",
        "DOI",
        "URL",
    ],
    "post-weblog": [
        "author",
        "title",
        "container-title",
        "volume",
        "page",
        "issued",
        "DOI",
        "URL",
    ],
    "regulation": [
        "title",
        "jurisdiction",
        "authority",
        "URL",
    ],
    "report": [
        "author",
        "title",
        "institution",
        "URL",
    ],
    "review": [
        "author",
        "title",
        "reviewed-title",
        "reviewed-genre",
        "container-title",
        "volume",
        "page",
        "issued",
        "DOI",
        "URL",
    ],
    "review-book": [
        "author",
        "title",
        "container-title",
        "volume",
        "page",
        "issued",
        "DOI",
        "URL",
    ],
    "software": [
        "author",
        "title",
        "publisher",
        "publisher-place",
        "version",
        "license",
        "URL",
    ],
    "song": [
        "author",
        "title",
        "container-title",
        "volume",
        "page",
        "issued",
        "DOI",
        "URL",
    ],
    "speech": [
        "author",
        "title",
        "event-date",
        "medium",
        "URL",
    ],
    "standard": [
        "authority",
        "title",
        "URL",
    ],
    "thesis": [
        "author",
        "title",
        "publisher",
        "publisher-place",
        "issued",
        "ISBN",
        "DOI",
        "URL",
    ],
    "treaty": [
        "title",
        "jurisdiction",
        "authority",
        "URL",
    ],
    "webpage": [
        "author",
        "title",
        "container-title",
        "page",
        "issued",
        "URL",
    ],
}


CSL_ALWAYS_SHOW = [
    "abstract",
    "archive",
    "archive_location",
    "archive-place",
    "archive-collection",
    "keyword",
    "language",
    "note",
    "annote",
    "source",
    "PMCID",
    "PMID",
    "DOI",
    "ISBN",
    "ISSN",
    "URL",
]


choices = {}
for attr in dir(citeproc.types):
    if not attr.startswith("__"):
        val = getattr(citeproc.types, attr)
        label = val.replace("-", " ").replace("_", " ")
        choices[attr] = (val, _(label))

TypeChoices = models.TextChoices("TypeChoices", choices)

# https://docs.citationstyles.org/en/stable/specification.html#locators
CSL_LOCATOR_CHOICES = [
    ("appendix", _("Appendix")),
    ("article-locator", _("Article locator")),
    ("book", _("Book")),
    ("canon", _("Canon")),
    ("chapter", _("Chapter")),
    ("column", _("Column")),
    ("elocation", _("Elocation")),
    ("equation", _("Equation")),
    ("figure", _("Figure")),
    ("folio", _("Folio")),
    ("issue", _("Issue")),
    ("line", _("Line")),
    ("note", _("Note")),
    ("opus", _("Opus")),
    ("page", _("Page")),
    ("paragraph", _("Paragraph")),
    ("part", _("Part")),
    ("rule", _("Rule")),
    ("section", _("Section")),
    ("sub-verbo", _("Sub-verbo")),
    ("supplement", _("Supplement")),
    ("table", _("Table")),
    ("timestamp", _("Timestamp")),
    ("title", _("Title")),
    ("verse", _("Verse")),
    ("volume", _("Volume")),
]
