# Generated by Django 5.0.6 on 2024-07-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literature",
            name="event",
        ),
    ]
