# Generated by Django 4.2.10 on 2024-02-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="literature",
            name="type",
            field=models.CharField(
                choices=[
                    ("article", "article"),
                    ("article-journal", "journal article"),
                    ("article-magazine", "magazine article"),
                    ("article-newspaper", "newspaper article"),
                    ("bill", "bill"),
                    ("book", "book"),
                    ("broadcast", "broadcast"),
                    ("chapter", "chapter"),
                    ("dataset", "dataset"),
                    ("entry", "entry"),
                    ("entry-dictionary", "entry (dictionary)"),
                    ("entry-encyclopedia", "entry (encyclopedia)"),
                    ("figure", "figure"),
                    ("graphic", "graphic"),
                    ("interview", "interview"),
                    ("legal_case", "legal case"),
                    ("legislation", "legislation"),
                    ("manuscript", "manuscript"),
                    ("map", "map"),
                    ("motion_picture", "motion picture"),
                    ("musical_score", "musical score"),
                    ("pamphlet", "pamphlet"),
                    ("paper-conference", "paper conference"),
                    ("patent", "patent"),
                    ("personal_communication", "personal communication"),
                    ("post", "post"),
                    ("post-weblog", "blog post"),
                    ("report", "report"),
                    ("review", "review"),
                    ("review-book", "review book"),
                    ("song", "song"),
                    ("speech", "speech"),
                    ("thesis", "thesis"),
                    ("treaty", "treaty"),
                    ("webpage", "webpage"),
                ],
                max_length=22,
                verbose_name="type",
            ),
        ),
    ]
