# Generated by Django 5.1.1 on 2024-10-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="literatureitem",
            old_name="key",
            new_name="citation_key",
        ),
    ]
