# Generated by Django 4.1.5 on 2023-01-22 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ORCID',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^(?:\\d{4}-){3}\\d{3}[\\d,x]')], verbose_name='ORCID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='family',
            field=models.CharField(blank=True, max_length=255, verbose_name='family name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='given',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='given name'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='last_synced',
            field=models.DateTimeField(blank=True, help_text='Last time the entry was synced with an online resource.', null=True, verbose_name='last synced'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='pages',
            field=models.CharField(blank=True, help_text='Either a single digit indicating the page number or two hyphen-separated digits representing a range.', max_length=32, null=True, validators=[django.core.validators.RegexValidator('^(\\d+-{1,2}?\\d+)$')], verbose_name='pages'),
        ),
    ]
