# Generated by Django 5.0.6 on 2024-07-09 17:01

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0002_remove_literature_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="literature",
            name="custom_author",
            field=django_jsonform.models.fields.JSONField(blank=True, default=list),
        ),
    ]
