# Generated by Django 5.1.3 on 2024-11-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0003_alter_literatureitem_citation_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='literatureitem',
            options={'ordering': ['-issued'], 'verbose_name': 'literature', 'verbose_name_plural': 'literature'},
        ),
    ]
