# Generated by Django 4.1.5 on 2023-01-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='number',
            new_name='issue',
        ),
    ]
