# Generated by Django 4.1.5 on 2023-01-11 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litman', '0003_alter_literature_author_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='pdf',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF'),
        ),
    ]
