const { Cite } = require('@citation-js/core')
import '@citation-js/plugin-bibjson'
import '@citation-js/plugin-bibtex'
import '@citation-js/plugin-csl'
import '@citation-js/plugin-doi'
import '@citation-js/plugin-ris'
import '@citation-js/plugin-wikidata'
import './import'
import './fetch'
import './replacer'
